use csadata;
delete from picklist where ptype ='OS';
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Centos6_small","Centos6_small","Centos6_small","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!rhel6_64Guest!RHEL6_base","RHEL6_base","RHEL6_base","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Centos6_devtest","Centos6_devtest","Centos6_devtest","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!LAMP","LAMP","LAMP","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("winpe64!winLonghorn64Guest!Win2008","Win2008","Win2008","OS","win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Centos6_core","Centos6_core","Centos6_core","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("winpe!winLonghornGuest!Win2003","Win2003","Win2003","OS","win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!rhel6_64Guest!RHEL6_LAMP","RHEL6_LAMP","RHEL6_LAMP","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Centos6_Desktop","Centos6_Desktop","Centos6_Desktop","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("winpe64!winLonghorn64Guest!Win2008_2","Win2008_2","Win2008_2","OS","win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux5!rhel5_64Guest!RHEL5_LAMP","RHEL5_LAMP","RHEL5_LAMP","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Cemtos5_orcl","Cemtos5_orcl","Cemtos5_orcl","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!rhel6_64Guest!Rhel6_Orcl11g","Rhel6_Orcl11g","Rhel6_Orcl11g","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux6!centos64Guest!Centos_orcl11g","Centos_orcl11g","Centos_orcl11g","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("linux5!rhel5_64Guest!RHEL5Oracle","RHEL5Oracle","RHEL5Oracle","OS","linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("winpe!winLonghornGuest!Winxp","Winxp","Winxp","OS","win");

use csadata;
delete from picklist where ptype='SW';
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("-none-","None","None","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("-none-","None","None","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("vz_transmageddon_25","vz_transmageddon_25","vz_transmageddon_25","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("Win_vCenter","Win_vCenter","Win_vCenter","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("DMA_Win_prep","DMA_Win_prep","DMA_Win_prep","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("SPoint2010","SPoint2010","SPoint2010","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("sp_vz_encoding1","sp_vz_encoding1","sp_vz_encoding1","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("vz_putty001","vz_putty001","vz_putty001","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("Oracle_XE_11.2","Oracle_XE_11.2","Oracle_XE_11.2","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("VMwaretools40","VMwaretools40","VMwaretools40","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("Orcl_11g","Orcl_11g","Orcl_11g","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("SharePoint2010","SharePoint2010","SharePoint2010","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("Lamp_Centos","Lamp_Centos","Lamp_Centos","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("IIS","IIS","IIS","SW","Win");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("DMA_Prep","DMA_Prep","DMA_Prep","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("sp_vpv","sp_vpv","sp_vpv","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("vz_transmageddon_21","vz_transmageddon_21","vz_transmageddon_21","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("Orcl_11g_bsae","Orcl_11g_bsae","Orcl_11g_bsae","SW","Linux");
insert into picklist (pvalue,pdisplay,pdesc,ptype,ptype1) values ("VMwaretools5i","VMwaretools5i","VMwaretools5i","SW","Linux");

